fa = "aust1305"

[[cs]]
fr = "Proto-Vietic"
to = "Muong Khen"
or = "Pogostick Man"
os = " from Thompson, Laurence C. (1976), “Proto-Viet-Muong Phonology”. Oceanic Linguistics Special Publications 13, Austroasiatic Studies II:1113 – 1203; Wikipedia contributors (2012). “Hanoi”. Wikipedia, the Free Encyclopedia. <http:"
so = [
    "aust1305_0",
    "aust1305_1",
    "aust1305_2",
    "aust1305_3",
    "aust1305_4",
]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "TonogenesisReg \tA \tB \tC \td",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "1. “Constricted” (laryngealized?)2. Terminates in a glottal stop if no final stop",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Presyllables don’t seem to have affected Muong much.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["h"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["cʰ"]
af = ["s"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["tʰ"]
af = ["h"]
en = ""
no = [
    "tones)",
    "first-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "([-sonorant]nly",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{kʰ,ɡʱ}"]
af = ["x"]
en = ""
no = [
    "much)",
    "this",
    "affected",
    "have",
    "to",
    "seem",
    "don’t",
    "([+labial,bilabial]resyllables",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "m",
    "n",
]
af = [
    "b",
    "d",
]
en = ""
no = [
    "tones)",
    "first-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "([-sonorant]nly",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{pj,bj}",
    "{tj,dj}",
    "{cj,ɟj}",
]
af = [
    "b",
    "d",
    "j",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ɓ",
    "ɗ",
]
af = [
    "b",
    "d",
]
en = ""
no = [
    "tones)",
    "first-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "([-sonorant]nly",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{n̥j,nj,ɲ̊j,ɲj}"]
af = ["ɲ"]
en = ""
no = ["j"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "[+nasal -voiced]",
    "[+semivowel -voiced]",
]
af = [
    "[+nasal +voiced]",
    "[+semivowel +voiced]",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["(h)ə{p,b}"]
af = ["t"]
en = "_l"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["m"]
af = ["∅"]
en = "_l"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["tɹ"]
af = ["tʰ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Miscellanea:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["∅"]
en = "tʰ[+vowel]_k (conjectured)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Vietic"
to = "Middle Vietnamese"
or = "Pogostick Man"
os = " from Thompson, Laurence C. (1976), “Proto-Viet-Muong Phonology”. Oceanic Linguistics Special Publications 13, Austroasiatic Studies II:1113 – 1203; Wikipedia contributors (2012). “Hanoi”. Wikipedia, the Free Encyclopedia. <http:"
so = [
    "aust1305_0",
    "aust1305_1",
    "aust1305_2",
    "aust1305_3",
    "aust1305_4",
]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Initials:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "bʱ",
    "{tʰ,dʱ}",
    "{t*ʰ,d*ʱ}",
    "{kʰ,ɡʱ}",
]
af = [
    "pʰ",
    "t",
    "tʰ",
    "kʰ",
]
en = ""
no = [
    "occur)",
    "may",
    "tones",
    "first-register",
    "only",
    "*ɡʱ,",
    "*kʰ",
    "(after",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "(h)ə{p,b}",
    "(h)ə{t,d}",
    "(h)ə{c,ɟ}",
    "(h)ə{k,ɡ}",
]
af = [
    "β",
    "dʲ",
    "ɟ",
    "ɡ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{pj,bj}",
    "{tj,dj}",
    "{cj,ɟj}",
]
af = [
    "{β,w}",
    "dʲ",
    "ɟ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ɓ",
    "ɗ",
]
af = [
    "m",
    "n",
]
en = ""
no = [
    "environment)",
    "this",
    "in",
    "occur",
    "can",
    "tones",
    "first-register",
    "only",
    "that",
    "seems",
    "it",
    "reason",
    "some",
    "([+fricative]or",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{n̥j,nj,ɲ̊j,ɲj}"]
af = ["ɲ"]
en = ""
no = [
    "nasal)",
    "palatal",
    "a",
    "as",
    "one",
    "this",
    "sticking",
    "I’m",
    "paper",
    "the",
    "in",
    "evidence",
    "other",
    "on",
    "based",
    "one;",
    "last",
    "the",
    "on",
    "bit",
    "a",
    "hedged",
    "have",
    "to",
    "me",
    "to",
    "appears",
    "([+plosive -voice]hompson",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["tʃ"]
af = ["Ω"]
en = ""
no = [
    "dialects)",
    "different",
    "in",
    "else",
    "something",
    "became",
    "was;",
    "form",
    "intermediate",
    "the",
    "what",
    "clue",
    "a",
    "have",
    "don’t",
    "I",
    "notation.",
    "own",
    "my",
    "is",
    "([+plosive -voice]his",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "[+nasal -voiced]",
    "[+semivowel -voiced]",
]
af = [
    "[+nasal +voiced]",
    "[+semivowel +voiced]",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "((h)ə)p",
    "d",
]
af = [
    "b",
    "t",
]
en = "_l"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["t"]
af = ["∅"]
en = "_ɹ (only first-register tones can occur in this environment)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "t*ʰ",
    "d",
    "ɡ",
]
af = [
    "tʰ",
    "t",
    "k",
]
en = "_w"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["t(ʰ?)"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{əkʰ,əɡɦj}"]
af = ["ɟ"]
en = ""
no = [
    "kludge)",
    "a",
    "of",
    "bit",
    "a",
    "just",
    "was",
    "this",
    "implied",
    "[+plosive -voice]hompson",
    "think",
    "(I",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Finals:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["∅"]
en = "{i,e}_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["j"]
en = "else"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "c",
    "ɲ",
]
af = [
    "t",
    "n",
]
en = "! [+vowel +front]_ (apparently the precursor to [+vowel]ietnamese short *a was treated as a short vowel here)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Thompson seems to list some changes as affecting Modern Vietnamese but I was unsure of where to put them so they’ll go here:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "a",
    "ɔ",
]
af = [
    "ɨə",
    "uə",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "In the original those first vowels were underlined.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Middle Vietnamese"
to = "Hanoi Vietnamese"
or = "Pogostick Man"
os = " from Thompson, Laurence C. (1976), “Proto-Viet-Muong Phonology”. Oceanic Linguistics Special Publications 13, Austroasiatic Studies II:1113 – 1203; Wikipedia contributors (2012). “Hanoi”. Wikipedia, the Free Encyclopedia. <http:"
so = [
    "aust1305_0",
    "aust1305_1",
    "aust1305_2",
    "aust1305_3",
    "aust1305_4",
]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "TonogenesisReg \tA \tB/D \tC",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "1. Tense when _S#; laryngealized elsewhere2. Laryngealized",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Initials:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["pʰ"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kʰ"]
af = ["x"]
en = ""
no = [
    "tones)",
    "first-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "(only",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{β,w}",
    "{dʲ,ɟ}",
]
af = [
    "v",
    "z",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɹ"]
af = ["z"]
en = ""
no = [
    "tones)",
    "first-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "(only",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["bl"]
af = ["z"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ml",
    "→",
    "mɲ",
]
af = [
    "ɲ",
    "([+plosive -voice]hompson",
    "seems",
]
en = ""
no = [
    "tones)",
    "second-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "only",
    "well;",
    "as",
    "[l]",
    "become",
    "have",
    "may",
    "this",
    "that",
    "indicate",
    "to",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "Ω",
    "cʰ",
]
af = [
    "s",
    "tɕ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Vowels:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɨ"]
af = ["i"]
en = "_(ə)w"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɛ"]
af = ["a"]
en = "_[+consonant +palatal]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Miscellanea:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["∅"]
en = "t[+vowel]_wk (conjectured)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Middle Vietnamese"
to = "Saigon Vietnamese"
or = "Pogostick Man"
os = " from Thompson, Laurence C. (1976), “Proto-Viet-Muong Phonology”. Oceanic Linguistics Special Publications 13, Austroasiatic Studies II:1113 – 1203; Wikipedia contributors (2012). “Hanoi”. Wikipedia, the Free Encyclopedia. <http:"
so = [
    "aust1305_0",
    "aust1305_1",
    "aust1305_2",
    "aust1305_3",
    "aust1305_4",
]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "TonogenesisReg \tA \tB/D \tC",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "1. Level when _S#; dipping otherwise2. Laryngealized",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Initials:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["pʰ"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kʰ"]
af = ["x"]
en = ""
no = [
    "tones)",
    "first-register",
    "with",
    "occurred",
    "have",
    "to",
    "seems",
    "(only",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{β,w}"]
af = ["bj~vj~v"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{bl,tl}"]
af = ["ʈ"]
en = ""
no = ["(?)"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "dʲ",
    "ɟ",
]
af = [
    "z",
    "j",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["m"]
af = ["∅"]
en = "_l"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "Ω",
    "cʰ",
]
af = [
    "ʂ",
    "ʈʂ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɹ"]
af = ["ʐ"]
en = ""
no = ["(sometimes?)"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Finals:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "c",
    "ɲ",
    "t",
    "n",
]
af = [
    "t",
    "n",
    "k",
    "ŋ",
]
en = "a_ (short "
no = ["/a/ only)"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "c",
    "ɲ",
]
af = [
    "t",
    "n",
]
en = "{i,e}_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{c,ɲ}"]
af = ["∅"]
en = "else"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Vowels:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ə"]
af = ["∅"]
en = "{i,ɨ}_{p,m.w}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ə"]
af = ["∅"]
en = "ɨ_j"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ə"]
af = ["∅"]
en = "u_{m,j}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "The contrast between short /a/ and short /ə/ is neutralized when _w{k,ŋ}",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["aː"]
en = "_{w,j}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ə(ː)",
    "ɛ",
]
af = [
    "ɨ",
    "ɛə",
]
en = "_[+velar]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɛ"]
af = ["a"]
en = "_[+consonant +palatal]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Miscellanea:",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["∅"]
en = "t[+vowel]_wk (conjectured) "
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []
