fa = "chib1249"

[[cs]]
fr = "Proto-Chibchan"
to = "Arhuaco"
or = "Pogostick Man"
os = " from Wheeler, Alva (1972), “Proto-Chibchan”. In Matteson, Esther, ed., Comparative Studies in Amerindian Languages 93 – 108"
so = ["chib1249_0"]
no = []

[[cs.ch]]
be = ["s"]
af = ["kh"]
en = "_([+vowel])k"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "s",
    "d",
]
af = [
    "z",
    "r",
]
en = "_([+vowel])j"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "h",
]
af = [
    "s",
    "∅",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["∅"]
af = ["u"]
en = "w_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["∅"]
en = "i_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["{j,∅}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["a"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "a_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ia"]
af = ["ə"]
en = ""
no = ["(“unspecifiedˈ)"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "[+consonant]ˈ[+vowel]([+consonant])_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "_([+consonant])ˈ[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Chibchan"
to = "Chibcha"
or = "Pogostick Man"
os = " from Wheeler, Alva (1972), “Proto-Chibchan”. In Matteson, Esther, ed., Comparative Studies in Amerindian Languages 93 – 108"
so = ["chib1249_0"]
no = []

[[cs.ch]]
be = ["b"]
af = ["p"]
en = "_[+vowel]kʷ"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]s"]
af = ["h"]
en = "n_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]"]
af = ["∅"]
en = "s_j (sometimes)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["h"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["{s,z}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["{w,∅}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["∅"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["n"]
af = ["{n,∅}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["∅"]
en = "_i, when unstressed"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["i"]
en = "_[+consonant]i"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["∅"]
en = "_u"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["u"]
af = ["o"]
en = "_[+consonant]a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["u"]
af = ["∅"]
en = "_a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["u"]
en = "_([+consonant])u"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["a"]
en = "_([+consonant])a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["e"]
en = "_([+consonant])e"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "a",
    "{e,i}",
]
af = [
    "i",
    "∅",
]
en = "[+consonant]ˈ[+vowel]([+consonant])_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "_([+consonant])ˈ[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["∅"]
en = "_ˈ[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Chibchan"
to = "Kogi"
or = "Pogostick Man"
os = " from Wheeler, Alva (1972), “Proto-Chibchan”. In Matteson, Esther, ed., Comparative Studies in Amerindian Languages 93 – 108"
so = ["chib1249_0"]
no = []

[[cs.ch]]
be = ["s"]
af = ["∅"]
en = "#_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["{ʃ,tʃ}"]
en = "_i"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["h"]
en = "_[+vowel]n"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "n[+vowel]s",
    "d[+vowel]s",
]
af = [
    "n([+vowel](s))",
    "ʒ([+vowel]ʒ)",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "s",
    "h",
]
af = [
    "{s,tʃ}",
    "{h,∅}",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["i"]
en = "[+consonant]([+vowel])_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "n",
    "j",
]
af = [
    "{n,∅}",
    "{j,∅}",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["a"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "a_ (sometimes)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["u"]
af = ["w"]
en = "_a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Chibchan"
to = "Marocacero"
or = "Pogostick Man"
os = " from Wheeler, Alva (1972), “Proto-Chibchan”. In Matteson, Esther, ed., Comparative Studies in Amerindian Languages 93 – 108"
so = ["chib1249_0"]
no = []

[[cs.ch]]
be = ["s"]
af = ["{ts,ʃ}"]
en = "_i"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["{s,ts}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "d([+vowel])j",
    "s([+vowel])j",
]
af = [
    "lʲ",
    "dʒ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["∅"]
en = "_i"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["a"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["ə"]
en = "o[+consonant]_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "[+consonant]ˈ[+vowel]([+consonant])_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "_([+consonant])ˈ[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Chibchan"
to = "Motilón"
or = "Pogostick Man"
os = " from Wheeler, Alva (1972), “Proto-Chibchan”. In Matteson, Esther, ed., Comparative Studies in Amerindian Languages 93 – 108"
so = ["chib1249_0"]
no = []

[[cs.ch]]
be = ["ɡ"]
af = ["∅"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["{s,x,tʃ~ʃ}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["{ʃ,tʃ}"]
en = "_i"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["x"]
en = "i_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["∅"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{w,m}"]
af = ["b"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s([+vowel])d"]
af = ["dʲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["∅"]
en = "[+vowel]_s"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["a"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "i",
    "→",
    "∅",
    "/",
    "a_",
    "(usually;",
    "sometimes",
    "the",
    "diphthong",
    "is",
    "retained",
    "or",
]
af = ["aj)"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["i"]
en = "i[+consonant]_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["u"]
af = ["∅"]
en = "a_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["u"]
af = ["∅"]
en = "_a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{ue,aja}"]
af = ["ə"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{u,i}"]
af = ["∅"]
en = "[+consonant]ˈ[+vowel]([+consonant])_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "_([+consonant])ˈ[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["u"]
en = "u[+consonant]_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["∅"]
en = "u_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Chibchan"
to = "Tunebo"
or = "Pogostick Man"
os = " from Wheeler, Alva (1972), “Proto-Chibchan”. In Matteson, Esther, ed., Comparative Studies in Amerindian Languages 93 – 108"
so = ["chib1249_0"]
no = []

[[cs.ch]]
be = [
    "ɡ",
    "ɡʷ",
]
af = [
    "∅",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{d([+vowel])s,n([+vowel])j}",
    "n([+vowel])s",
]
af = [
    "r",
    "{[+vowel]s[+vowel],r}",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d([+vowel])j"]
af = ["r([+vowel])"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["r"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["h"]
en = "_([+vowel])[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "tʃ",
]
af = [
    "tʃ",
    "s",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "m",
    "n",
    "h",
    "j",
]
af = [
    "b",
    "{n,r,∅}",
    "{h,∅}",
    "{j,∅}",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["a"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ai"]
af = ["e"]
en = "if the *a is not stressed"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["∅"]
en = "_u"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["a"]
en = "_[+consonant]a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{a,i}"]
af = ["∅"]
en = "[+consonant]ˈ[+vowel]([+consonant])_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "_([+consonant])ˈ[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["∅"]
en = "u_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["i"]
en = "“conditioning undeterminedˈ"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []