fa = "drav1251"

[[cs]]
fr = "Standard Tamil"
to = "Colloquial Tamil"
or = "schwatever"
os = " from Shiffman, Harold F. A Reference Grammar on Spoken Tamil"
so = ["drav1251_0"]
no = []

[[cs.ch]]
be = ["aj"]
af = ["eː"]
en = ""
no = [
    "words)ˈ",
    "multisyllabic",
    "in",
    "initially",
    "never",
    "monosyllables,",
    "in",
    "finally",
    "never",
    "“(exception:",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "avu",
    "aji",
]
af = [
    "aw",
    "aj",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "i",
    "u",
]
af = [
    "e",
    "o",
]
en = "_[+consonant]a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{k,v}"]
af = ["∅"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "aː",
    "eː",
    "iː",
    "oː",
    "uː",
]
af = [
    "a",
    "ɛ",
    "i",
    "o",
    "u",
]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "am",
    "an",
    "{aːm,aːn}",
]
af = [
    "õ",
    "æ̃",
    "ã",
]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{om,on}",
    "{em,en}",
    "{oːm,oːn}",
    "{eːm,eːn}",
]
af = [
    "ɔ̃",
    "ɛ̃",
    "õ",
    "ẽ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["um"]
af = ["ũ"]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["∅"]
af = ["ɨ"]
en = "_[+nasal]#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{ɭ,ɽ}"]
af = ["∅"]
en = ""
no = [
    "lengthening)",
    "compensatory",
    "some",
    "contributing",
    "and",
    "so",
    "much",
    "very",
    "latter",
    "the",
    "(sporadic,",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "l",
    "ɭ",
]
af = [
    "lːʉ",
    "ɭːʉ",
]
en = "_#([+consonant])[+vowel -long]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["∅"]
af = ["ʉ"]
en = "{l,ɭ}_# if {[+diphtong],[+vowel]ː} previously in the lexeme"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["r"]
af = ["ɾ"]
en = ""
no = [
    "dialectsˈ",
    "most",
    "“in",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɽ"]
af = ["ɭ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{ɾ,l,ɭ}"]
af = ["∅"]
en = "[+vowel]_[+plosive]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "i",
    "u",
]
af = [
    "ɨ",
    "ʉ",
]
en = "short only when unstressed ! in #[+syllable]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ɨ",
    "ʉ",
]
af = ["∅"]
en = "! _#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["∅"]
af = ["{ɨ,ʉ}"]
en = "to break up clusters"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["n"]
af = ["ŋ"]
en = "_{k,ɡ}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "i(ː)",
    "e(ː)",
]
af = [
    "u(ː)",
    "o(ː)",
]
en = "{m,v,p}_[+consonant]̣"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["∅"]
en = "[+vowel -front]_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["jːi"]
en = "[+vowel +front]_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tː",
    "nt",
]
af = [
    "cː",
    "ɲc",
]
en = "{i,j}_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ʈk"]
af = ["kː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "n",
    "tː",
]
af = [
    "n̪",
    "t̪ː",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɳ"]
af = ["n"]
en = ""
no = [
    "development)ˈ",
    "dialect",
    "and",
    "“(sporadic",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɭ"]
af = ["l"]
en = ""
no = [
    "sporadic)ˈ",
    "“(again,",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["c"]
af = ["s"]
en = "_{a,o,u,e}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["cː"]
af = ["tʃː"]
en = ""
no = [
    "dialects)ˈ",
    "“(most",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "o",
    "e",
]
af = [
    "u",
    "i",
]
en = "_[+consonant]{u,i} “(highly sporadic)ˈ"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "“There’s also only a few changes necessary to turn this into the British dialect (which didn’t merge retroflexes with alveolars):”",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "i(ː)",
    "e(ː)",
]
af = [
    "u(ː)",
    "o(ː)",
]
en = "_ɭ"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "e[+consonant]ə",
    "o[+consonant]ə",
]
af = [
    "[+consonant]eː",
    "[+consonant]oː",
]
en = "#_ "
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []
