so = [
    " from Wikipedia contributors (2013), “Albanian language”. Wikipedia, the Free Encyclopedia. <http:",
    "i}",
    " from http:",
    " the latter citing Wikipedia contributors (2013), “Armenian Language”. Wikipedia, the Free Encyclopedia. <http:",
    " Alex Fink, and Tropylium, the former two citing Wikipedia contributors (2013), “Proto-Indo-Iranian language”. Wikipedia, the Free Encyclopedia. <https:",
    " from Matasović (2009), Etymological Dictionary of Proto-Celtic (ed. Lubotsky).",
    " as in [nizdos] for *nisdos, are assumed to apply”",
    " the latter citing Willis (David), “Old and Middle Welsh”",
    " from Wikipedia contributors (2013), “Dacian language”. Wikipedia, the Free Encyclopedia. <https:",
    "j} {u,w} → j w ",
    " from Wright, Joseph (1910). Grammar of the Gothic Language, 2nd Ed.; and Wikipedia contributors (2014). “Gothic language”. Wikipedia, the Free Encyclopedia. <http:",
    "”V}_",
    " the latter citing Wikipedia contributors (2014), “Anglo-Frisian languages”. Wikipedia, the Free Encyclopedia. <https:",
    " from Wikipedia contributors (2011), “Phonological history of English”. Wikipedia, the Free Encyclopedia. <http:",
    " from Moore, Samuel (1919), Historical Outlines of English Phonology and Midd le English Grammar for Courses in Chaucer, Middle English, and the History of the English Language; and Wikipedia contributors (2011), “Middle English phonology”. Wikipedia, the Free Encyclopedia. <http:",
    " from FireSpeakerWiki contributors (2013), “English sound changes”. FireSpeakerWiki. <http:",
    " from Wikipedia contributors (2014), “Phonological history of Scots”. Wikipedia, the Free Encyclopedia. <https:",
    " from personal research",
    " the former from Wikipedia contributors (2016), “Forth and Bargy dialect”. Wikipedia, the Free Encyclopedia. <https:",
    " from Wikipedia contributors (2011), “Old Frisian”. Wikipedia, the Free Encyclopedia. <http:",
    " from Wikipedia contributors (2014), “Old Dutch”. Wikipedia, the Free Encyclopedia. <https:",
    " from Wikipedia contributors (2014), “Middle Dutch”. Wikipedia, the Free Encyclopedia. <https:",
    " from Wikipedia contributors (2014), “Dutch Phonology”. Wikipedia, the Free Encyclopedia. <https:",
    " from Behr, Hans-Joahim, Ingrid Bennewitz, et al. (2004). Die Bamberg (BA)-Braunschweiger (BS) Grammatik des Alt-und Mittelhochdeutschen im Internet. <https:",
    " from Wikipedia contributors (2014), “Old Saxon phonology”. Wikipedia, the Free Encyclopedia. <https:",
    " from Theiling, Henrik, http:",
    " from Wikipedia contributors (2015), “Vandalic language”. Wikipedia, the Free Encyclopedia. <https:",
    " from Tucker, R. Whitney (1969), “Chronology of Greek Sound Changes”. The American Journal of Philology 90(1):36 – 47; and Wikipedia contributors (2013), “Ancient Greek dialects”. Wikipedia, the Free Encyclopedia. <https:",
    "e}",
    "eu,au} → u",
    " from Kobayashi, Masato (2004), Historical Phonology of Old Indo-Aryan Consonants",
    " from Shukla, Shaligram (1974), “Phonological change and dialect variation in Middle-Indo-Aryan”. In Anderson, J., and C. Jones (Eds.), Historical Linguistics II:391-401.",
    "ɡ́ʱ} ɡʷʱ → b d ɡ ɡʷ",
    " in http:",
    "d} → ∅ ",
    " from Ramat, Anna Giacrole and Paolo Ramat, The Indo-European Languages, and other sources",
    " a lot of the special characters were replaced with 〈?〉. In many cases these have been replaced with 〈∅〉 because it was likely that this was what was meant, but conditional 〈?〉 has either been left alone or attempted to have been filled in from context. In some cases, conditional 〈?〉 may have been used to mark stress or syllable boundaries. Take such changes with a grain of salt and use at your own risk.",
    "v,s}",
    " from Boyd-Bownam, P. From Latin to Romance in Sound Charts",
    " a lot of the special characters were replaced with 〈?〉. In many cases these have been replaced with 〈∅〉 because it was likely that this was what was meant, but conditional 〈?〉 has either been left alone or attempted to have been filled in from context. In some cases, conditional 〈?〉 may have been used to mark stress or syllable boundaries. Take such changes with a grain of salt and use at your own risk. Further, Mecislau gives some dual-output changes, which distinguish between vulgar and “semi-learned” outcomes.",
    " from Grandgent, Charles Hall (1905), An outline of the phonology and morphology of old Provençal, Revised Edition",
    " from Wikipedia contributors (2014), “Rhaeto-Romance languages”. Wikipedia, the Free Encyclopedia. <https:",
    " from Jensen, A Comparative Study of Romance, as well as other sources",
    " “mainly” from http:",
    " the former citing Penny, Ralph (2002), A History of the Spanish Language, 2nd Ed. Cambridge University Press; and Lipski, John (1994), Latin American Spanish. Longman Pub Group.",
]
