fa = "khoe1241"

[[cs]]
fr = "Proto-Khoe"
to = "Ç̬Ana"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["ǂ̃n"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!"]
af = ["!~k"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!x"]
af = ["x"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!̬"]
af = ["ɡ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!̃(n)"]
af = ["ŋ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["{ts~tsʰ,ts,s}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j"]
en = "_[+vowel +front]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "ÇAni"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["ǂ̃n"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!̬",
    "!̃",
]
af = [
    "!~k",
    "!̬~ɡ",
    "!̃(n)~ŋɡ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!x"]
af = ["!x~x"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["{ts,s}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j~ʔ"]
en = "_[+vowel +front]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["h~ʔ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "Buga"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["ǂ̃"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!ˀ",
    "!̬",
    "!̃",
]
af = [
    "k",
    "∅",
    "ɡ",
    "ŋɡ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!x"]
af = ["x"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["!̃n"]
af = ["ŋɡj~!̃"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["{ts~tsʰ,ts,s}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "Kxoe"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["!̃(n)"]
af = ["ǂ̃"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!ˀ",
    "!",
    "!̃",
]
af = [
    "k",
    "∅",
    "ɡ",
    "ŋɡ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!x",
    "!̃n",
]
af = [
    "x",
    "ŋɡj~!̃",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "dz",
]
af = [
    "{ç,tç}",
    "dʒ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kʰ"]
af = ["kx"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "Nama"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["k"]
af = ["ɡ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{ǀˀ,ǀxʼ}"]
af = ["ǀ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["{ǂ̃,ǂ}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!ˀ",
    "!̃n",
]
af = [
    "!ɡ",
    "~",
    "!̃",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ǂ",
    "{ǂ̃n,ǂˀ,ǂxʼ}",
]
af = [
    "ǂɡ",
    "ǂ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{ǁˀ,ǁxʼ}"]
af = ["ǁ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "dz",
    "kxʼ",
]
af = [
    "{ts,s}",
    "d",
    "∅",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "Naro"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["ǂ̃"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "dz",
]
af = [
    "{ts~tsʰ,ts,s}",
    "dz~ts",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kʰ"]
af = ["{kx,k}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "!Ora"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["ǂ̃"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!̃n",
]
af = [
    "!",
    "!̃",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ǂ̃n"]
af = ["ǂ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ǁˀ"]
af = ["{ǁˀ,ǁ}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["{ts,s}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "Teti"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["j"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!ˀ",
    "!̬",
    "!̃(n)",
    "!x",
]
af = [
    "k",
    "∅",
    "ɡ",
    "ŋ",
    "x",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ǂ",
    "ǂ̃n",
    "ǂˀ",
]
af = [
    "c",
    "ɲ",
    "ʔj",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ǁˀ",
    "ǁxʼ",
]
af = [
    "{ǁˀ,∅}",
    "ǁˀ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "dz",
    "kxʼ",
]
af = [
    "{ts~tsʰ,ts,s}",
    "z",
    "kʼ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j~ʔj"]
en = "_[+vowel +front]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["h~ʔj"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "TsÊixa"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = [
    "ǀ̃(n)",
    "ǀxʼ",
]
af = [
    "j",
    "ǀˀ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!",
    "!ˀ",
    "!̬",
    "!̃(n)",
    "!x",
]
af = [
    "k",
    "∅",
    "ɡ",
    "ŋɡ",
    "x",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ǂ̃n",
    "ǂxʼ",
]
af = [
    "ɲ",
    "ǂˀ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ǁxʼ"]
af = ["ǁˀ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "dz",
    "kxʼ",
]
af = [
    "{ts~tsʰ,ts,s}",
    "z",
    "kʼ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j~ʔj"]
en = "_[+vowel +front]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["h~j"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Khoe"
to = "Ç̬Ui"
or = "Pogostick Man"
os = " from Rainer (1984), “Studying the linguistic and ethno-history of the Khoe-speaking (central Khoisan) peoples of Botswana, research in progress”. In Botswana Notes and Records 16:19 – 35."
so = ["khoe1241_0"]
no = []

[[cs.ch]]
be = ["ǀ̃(n)"]
af = ["ǂ̃n"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "!̃",
    "!x",
]
af = [
    "!̃(n)",
    "!x~x",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["{ts~tsɦ,s}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["j"]
en = "_[+vowel +front]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["ɦ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []