fa = "mand1469"

[[cs]]
fr = "Proto-Mande"
to = "Bobo"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "{kʼ,ɡ}",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["d"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["{s,j}"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["ɡ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "ɡb",
]
af = [
    "k",
    "ɡw",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Busa"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "kpʼ",
]
af = [
    "{kp,k}",
    "ɡb",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["i"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Dan"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kpʼ"]
af = ["ɡb"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Guro"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "p",
    "f",
]
af = [
    "f",
    "v",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "{kpʼ,ɡb}",
]
af = [
    "p",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Kono-Vai"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["d"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["s"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{ɡ,w,kp}",
    "kpʼ",
    "ɡb",
]
af = [
    "k",
    "kp",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Southwest Mande"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["f"]
af = ["p"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{tʼ,d}",
    "{kʼ,ɡ}",
]
af = [
    "l",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["s"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["ɡ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "kpʼ",
    "ɡb",
]
af = [
    "{k,[+vowel +back]}",
    "kp",
    "[+vowel +back]",
]
en = ""
no = [
    "is)",
    "〈[+vowel +back]〉",
    "this",
    "what",
    "unclear",
    "(it’s",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Mandekan"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["d"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["s"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "{k,ɡ,kp}",
    "{kpʼ,ɡb}",
]
af = [
    "s",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "w",
    "j",
]
af = [
    "k",
    "dʒ",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Mano"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["f"]
af = ["v"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kpʼ"]
af = ["ɡb"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Mwa"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["f"]
af = ["v"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kpʼ"]
af = ["ɡb"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "San"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "kʼ",
]
af = [
    "t",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["d"]
af = ["l"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "kpʼ",
]
af = [
    "k",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Sembla"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["f"]
af = ["d"]
en = ""
no = [
    "really)",
    "(yes,",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "{kʼ,ɡ,w}",
]
af = [
    "{t,d}",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["d"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["s"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɡb"]
af = ["b"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["j"]
af = ["dʒ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["ɲ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Soninka"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tʼ",
    "{kʼ,ɡ}",
]
af = [
    "{t,d}",
    "k",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["j"]
en = ""
no = ["?"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["{w,ŋ}"]
af = ["j"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "ɡb",
]
af = [
    "k",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Mande"
to = "Susu"
or = "Pogostick Man"
os = " from Dwyer, David J. (1987"
so = ["mand1469_0"]
no = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "NB: These changes only deal with consonants.",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["tʼ"]
af = ["t"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["d"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["z"]
af = ["s"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["x"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŋ"]
af = ["j"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "kp",
    "ɡb",
]
af = [
    "k",
    "b",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []
