fa = "TODO"

[[cs]]
fr = "Proto-Muskogean"
to = "Proto-Eastern Muskogean"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["s0"]
no = []

[[cs.ch]]
be = ["θ"]
af = ["ɬ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["xʷ"]
af = ["f"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel +consonant +weak]"]
af = ["∅"]
en = "_[+vowel]#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Eastern Muskogean"
to = "Alabama"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["ʃ"]
af = ["ts"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["k[+vowel]"]
af = ["∅"]
en = "[+vowel]_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["k"]
af = ["∅"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ts",
    "x",
]
af = [
    "s",
    "h",
]
en = "_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Eastern Muskogean"
to = "Creek"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["[+vowel]1k[+vowel]2"]
af = ["[+vowel]2ː"]
en = "#(([+consonant])[+vowel]([+consonant]))([+consonant])_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]1k"]
af = ["∅"]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ʃ"]
af = ["ts"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kʷ"]
af = ["k"]
en = "#_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kʷ"]
af = ["b"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+plosive]"]
af = ["[+plosive +voice]"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["h"]
af = ["x"]
en = "_%"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]0x[+vowel]0"]
af = ["[+vowel]0ː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Initial vowels lost?",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["w"]
en = "a_o"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["h"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["m"]
af = ["ŋ"]
en = "_k"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "ts and t alternate before k",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["kl"]
af = ["kː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+consonant]ː"]
af = ["[+consonant -long]"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Eastern Muskogean"
to = "Hitchiti"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["ʃ"]
af = ["ts"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]"]
af = ["∅"]
en = "[+vowel]k_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["j"]
en = "[+vowel]0_[+vowel]0"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["h"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Eastern Muskogean"
to = "Korasati"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["ʃ"]
af = ["ts"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]k[+vowel]"]
af = ["ˈ[+vowel]"]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["k"]
af = ["∅"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ts"]
af = ["s"]
en = "_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["nt"]
af = ["tː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["h"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Eastern Muskogean"
to = "Mikasuri"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["[+vowel]"]
af = ["∅"]
en = "[+vowel]k_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["j"]
en = "[+vowel]0_[+vowel]0"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["tʃ"]
af = ["s"]
en = "_[+consonant] ! _k"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "ʃ",
    "x",
]
af = [
    "ts",
    "h",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Eastern Muskogean"
to = "Seminole"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = [
    "ʃ",
    "x",
]
af = [
    "ts",
    "h",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["tl"]
af = ["tː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Muskogean"
to = "Proto-Western Muskogean"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = [
    "ts",
    "tʃ",
]
af = [
    "s",
    "ts",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["θ"]
af = ["n"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["ʃ"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["x"]
af = ["h"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "[+consonant]1[+weak]",
    "[+consonant]2[+weak]",
]
af = [
    "ʔ",
    "h",
]
en = "[+vowel]_[+vowel]#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["[+vowel]"]
af = ["∅"]
en = "[+vowel]{k,ʔ,h}_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["xʷ"]
af = ["h"]
en = "%_{o,i}([+consonant])#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["o"]
en = "xʷ_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "oj",
    "aj",
]
af = [
    "iː",
    "{aː,iː}",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["i"]
af = ["∅"]
en = "#([+consonant])[+vowel]([+consonant])([+consonant])[+vowel]([+consonant])([+consonant])_# (sporadic in the case of other vowels)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "tl",
    "st",
]
af = [
    "lː",
    "tː",
]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Western Muskogean"
to = "Chickasaw"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["h"]
af = ["∅"]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["aw"]
af = ["o"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["xʷɬ"]
af = ["ɬː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Western Muskogean"
to = "Choctaw"
or = "Pogostick Man"
os = " from Booker, Karen (2005), “Muskogean Historical Phonology”. In Hardy, Heather Kay, and Janine Scancarelli, eds., Native Languages of the Southeastern United States 246 – 298"
so = ["0"]
no = []

[[cs.ch]]
be = ["ʔ"]
af = ["∅"]
en = "_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["xʷ"]
af = ["h"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɬh"]
af = ["ɬː"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["a"]
af = ["o"]
en = "_w"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["k"]
en = "_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []
