so = [
    " from Upson, B.W., and Robert E. Longacre (1965), “Proto-Chatino Phonology”. International Journal of American Linguistics 31(4):312 – 322",
    " from Rensch, Calvin R. (1977), “Classification of the Otomanguean Languages and the Position of Tlapanec”. Summer Institute of Linguistics Publications in Linguistics 55:53 – 108",
]
