so = [
    " from Egurtzegi, Ander (2013), “Phonetics and Phonology”, in Basque and Proto-Basque. <https:",
    " from Egurtzegi, Ander (2013), ”Phonetics and Phonology”, in Basque and Proto-Basque. <https:",
]
