[package]
name = "diachronica_regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
typed-json = "0.1.1"
serde_json = "1.0.112"
serde = { version = "1.0", features = ["derive"] }