fa = "_elamodravidian"

[[cs]]
fr = "Proto-Elamo-Dravidian"
to = "Proto-Dravidian"
or = "Pogostick Man"
os = " from McAlpin, David W. (1974), “Toward Proto-Elamo-Dravidian”. Language 50(1):89 – 101"
so = ["s0"]
no = []

[[cs.ch]]
be = ["w"]
af = ["v"]
en = "#_{i,e}l[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["v"]
en = "[+vowel]_"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "k",
    "ʃk",
]
af = [
    "k*",
    "kː",
]
en = "[+vowel]_[+vowel] (the asterisk-marked k is what [+diphtong]c[+affricate]lpin terms “weak kˈ, which tends to drop out in morphology)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["t"]
af = ["∅"]
en = "#_[+vowel]r[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["t"]
af = ["{t,ʈ}"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["rt"]
af = ["ʈ"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["p"]
af = ["v"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["t"]
en = "#_[+vowel][+liquid][+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["j"]
en = "[+vowel]_{[+vowel],#}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["∅"]
en = "#[+vowel]_{r̀,l}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["∅"]
en = "[+consonant]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["s"]
af = ["∅"]
en = "[+vowel]_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["r̀"]
af = ["r̲"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŕ"]
af = ["r"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "n",
    "nː",
    "rn",
]
af = [
    "{n̲,r}",
    "n̲(ː)",
    "ɳ",
]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["nː"]
af = ["n̲(ː)"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["nr̀"]
af = ["n̲r̲"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "l",
    "lː",
]
af = [
    "{l,ɭ}",
    "ɭ(ː)",
]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["ɭ"]
en = "[+vowel]_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = []
af = []
en = ""
no = [
    "Proto-Dravidian retained long vowels, possibly from the simplification of consonant clusters and/or deletion of intervocalic consonants with compensatory lengthening and/or the resulting vowels in hiatus merging",
    "",
]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs]]
fr = "Proto-Elamo-Dravidian"
to = "Achaemanid Elamite"
or = "Pogostick Man"
os = " from McAlpin, David W. (1974), “Toward Proto-Elamo-Dravidian”. Language 50(1):89 – 101"
so = ["0"]
no = []

[[cs.ch]]
be = ["{i,e,u}"]
af = ["∅"]
en = "#_{t,n}a"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["e"]
af = ["{e,i}"]
en = "#[+consonant]_[+consonant]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["w"]
af = ["ú"]
en = "[+vowel]_ ([+diphtong]c[+affricate]lpin uses the accented-vowel notation due to some apparent height-contrast neutralizations before "
no = ["/a/)"]
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = [
    "k",
    "ŋk",
    "ŋkː",
]
af = [
    "∅",
    "k",
    "kː",
]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["mp"]
af = ["p(ː)"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["c"]
af = ["s"]
en = "#_{a,u}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ɲc"]
af = ["ns"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["r̀"]
af = ["r"]
en = "[+vowel]_{[+vowel],[+consonant]}"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["ŕ"]
af = ["rː"]
en = "[+vowel]_[+vowel]"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["nr̀"]
af = ["nr"]
en = ""
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["l"]
af = ["n"]
en = "[+vowel]_#"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []

[[cs.ch]]
be = ["v"]
af = ["m"]
en = "#_[+vowel] (?)"
no = []
ta = [
    "generated",
    "unchecked",
]
ty = []